osx_image: xcode10.2.1
language: objective-c
install: true
script: Scripts/cibuild
deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  file: Neptune.framework.zip
  skip_cleanup: true
  on:
    tags: true
